<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="operationalCapability" nsURI="http://www.example.org/operationalCapability"
    nsPrefix="operationalCapability">
  <eClassifiers xsi:type="ecore:EClass" name="Capabilty" eSuperTypes="#//SpecializableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="involves" lowerBound="1"
        upperBound="-1" eType="#//InvolvableElement" eOpposite="#//InvolvableElement/isInvolvedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Capabilty"
        eOpposite="#//Capabilty/isExtendedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isExtendedBy" upperBound="-1"
        eType="#//Capabilty" eOpposite="#//Capabilty/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Capabilty" eOpposite="#//Capabilty/isIncludedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isIncludedIn" eType="#//Capabilty"
        eOpposite="#//Capabilty/includes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecializableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializes" eType="#//SpecializableElement"
        eOpposite="#//SpecializableElement/isSpecializedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSpecializedBy" eType="#//SpecializableElement"
        eOpposite="#//SpecializableElement/specializes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SpecializableElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvolvableElement" abstract="true" eSuperTypes="#//SpecializableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInvolvedIn" lowerBound="1"
        upperBound="-1" eType="#//Capabilty" eOpposite="#//Capabilty/involves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//InvolvableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//InvolvableElement"/>
</ecore:EPackage>
